spring.application.name=cacharrito
spring.datasource.url=jdbc:mysql://mysql-d8c41e2-mi-cacharrito.l.aivencloud.com:14937/defaultdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true