spring.application.name=cacharrito
spring.datasource.url=jdbc:mysql://localhost/cacharrito
spring.datasource.username=root
spring.datasource.password=342007maria13

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update